all:
	g++  -std=c++11 videocapture.cpp -o	videocapture `pkg-config --cflags --libs opencv`

change:
	g++ -std=c++11 videocapture_changes.cpp -o videocapture_changes `pkg-config --cflags --libs opencv`
